"""add business cancellation fee percent and order cancellation fee

Revision ID: 61adc0f3f8c1
Revises: 95eb48051d95
Create Date: 2026-07-28 22:15:49.903217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61adc0f3f8c1'
down_revision: Union[str, Sequence[str], None] = '95eb48051d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'businesses',
        sa.Column('late_cancellation_fee_percent', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('orders', sa.Column('cancellation_fee_xof', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancellation_fee_xof')
    op.drop_column('businesses', 'late_cancellation_fee_percent')
    # ### end Alembic commands ###
