"""add product initial_stock

Revision ID: 663d1e2f88dc
Revises: 4b66ea66709c
Create Date: 2026-07-27 16:17:42.632135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663d1e2f88dc'
down_revision: Union[str, Sequence[str], None] = '4b66ea66709c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('initial_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Backfill: existing rows' baseline is whatever their current stock is.
    op.execute("UPDATE products SET initial_stock = quantity_in_stock WHERE track_inventory = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'initial_stock')
    # ### end Alembic commands ###
