"""add order return_requested_at

Revision ID: 95eb48051d95
Revises: 663d1e2f88dc
Create Date: 2026-07-28 18:08:35.095071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eb48051d95'
down_revision: Union[str, Sequence[str], None] = '663d1e2f88dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('return_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'return_requested_at')
    # ### end Alembic commands ###
